-- liquibase formatted sql
-- changeset GM:init_data_20260629001

INSERT INTO `manage_user_info`(`id`, `username`, `real_name`, `password_hash`, `email`, `level`, `creator`, `updater`, `create_time`, `update_time`) VALUES (1, 'admin', '', '$2a$10$6.JwdQgDFethrdMC6uJeautw4EGZ5UsXfFtmIXYqJEZpHJQ2lAq92', '', NULL, '', '', 1782553661000, NULL);
INSERT INTO `manage_role_info`(`id`, `role_code`, `role_name`, `level`, `desc`, `creator`, `updater`, `create_time`, `update_time`) VALUES (1, 'ROLE_ADMIN', '', NULL, '', '', '', 1782553661000, NULL);
INSERT INTO `manage_user_role`(`id`, `username`, `role_code`, `creator`, `updater`, `create_time`, `update_time`) VALUES (1, 'admin', 'ROLE_ADMIN', '', '', 1782553661000, NULL);

INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (1, 'menu.sys-permission', 'sys-permission', '/sys-permission', 1, 'DEFAULT_LAYOUT', 1, 'icon-lock', 0, 1, 100, 1, '', '', 1782553661000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (2, 'menu.user-control', 'user-control', 'user-control', 0, 'config/user-control/index', 1, NULL, 1, 2, 0, 1, '', '', 1782553661000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (3, 'menu.role-control', 'role-control', 'role-control', 0, 'config/role-control/index', 1, NULL, 1, 2, 1, 1, '', '', 1782553661000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (4, 'menu.system-router-config', 'system-router-config', 'system-router-config', 0, 'config/system-router-config/index', 1, NULL, 1, 2, 2, 1, '', '', 1782553661000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (5, 'menu.server-api-config', 'server-api-config', 'server-api-config', 0, 'config/server-api-config/index', 1, NULL, 1, 2, 3, 1, '', '', 1782553661000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (6, 'menu.user-member', 'user-member', '/user-member', 1, 'DEFAULT_LAYOUT', 1, 'icon-user-group', 0, 1, 1, 1, '', '', 1782556543842, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (7, 'menu.mission', 'mission', '/mission', 1, 'DEFAULT_LAYOUT', 1, 'icon-bookmark', 0, 1, 2, 1, '', '', 1782556800249, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (8, 'menu.order', 'order', '/order', 1, 'DEFAULT_LAYOUT', 1, 'icon-ordered-list', 0, 1, 3, 1, '', '', 1782556880527, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (9, 'menu.promotion', 'promotion', '/promotion', 1, 'DEFAULT_LAYOUT', 1, 'icon-gift', 0, 1, 4, 1, '', '', 1782557000624, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (10, 'menu.report', 'report', '/report', 1, 'DEFAULT_LAYOUT', 1, 'icon-bar-chart', 0, 1, 5, 1, '', '', 1782557061927, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (11, 'menu.sys-setting', 'sys-setting', '/sys-setting', 1, 'DEFAULT_LAYOUT', 1, 'icon-settings', 0, 1, 6, 1, '', '', 1782557066632, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (12, 'menu.member-list', 'members', '/members', 0, 'user-member/members/index', 1, '', 6, 2, 0, 1, '', '', 1782568037787, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (13, 'menu.mission.list', 'mission-list', '/mission-list', 0, 'mission/mission-list/index', 1, '', 7, 2, 0, 1, '', '', 1782569365281, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (14, 'menu.mission.plan', 'mission-plan', '/mission-plan', 0, 'mission/plan/index', 1, '', 7, 2, 1, 1, '', '', 1782569452737, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (15, 'menu.mission.approval', 'mission-approval', '/mission-approval', 0, 'mission/approval/index', 1, '', 7, 2, 2, 1, '', '', 1782569611630, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (16, 'menu.order.deposit', 'deposit-order', '/deposit-order', 0, 'order/deposit/index', 1, '', 8, 2, 0, 1, '', '', 1782569841910, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (17, 'menu.order.withdraw', 'withdraw-order', '/withdraw-order', 0, 'order/withdraw/index', 1, '', 8, 2, 1, 1, '', '', 1782570430264, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (18, 'menu.order.transfer', 'transfer-order', '/transfer-order', 0, 'order/transfer/index', 1, '', 8, 2, 2, 1, '', '', 1782570515005, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (19, 'menu.order.payment', 'payment-order', '/payment-order', 0, 'order/payment/index', 1, '', 8, 2, 3, 1, '', '', 1782570584205, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (20, 'menu.order.consolidation', 'consolidation-order', '/consolidation-order', 0, 'src/views/order/consolidation/index.vue', 1, '', 8, 2, 4, 1, '', '', 1782570626060, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (21, 'menu.order.approval', 'order-approval', '/order-approval', 0, 'order/approval/index', 1, '', 8, 2, 5, 1, '', '', 1782570682436, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (22, 'menu.order.log', 'order-log', '/order-log', 0, 'order/log/index', 1, '', 8, 2, 6, 1, '', '', 1782570723366, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (23, 'menu.promotion.prize-config', 'prize-config', '/prize-config', 0, 'promotion/prize-config/index', 1, '', 9, 2, 0, 1, '', '', 1782609363931, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (24, 'menu.promotion.lucky-draw', 'lucky-draw', '/lucky-draw', 0, 'promotion/lucky-draw/index', 1, '', 9, 2, 1, 1, '', '', 1782609419698, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (25, 'menu.report.summary', 'summary', '/summary', 0, 'report/summary/index', 1, '', 10, 2, 0, 1, '', '', 1782609498724, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (26, 'menu.leaderboard', 'leaderboard', '/leaderboard', 1, 'DEFAULT_LAYOUT', 1, 'icon-sort', 0, 1, 7, 1, '', '', 1782609975846, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (27, 'menu.leaderboard.index', 'leaderboard-index', '/leaderboard-index', 0, 'leaderboard/index', 1, '', 26, 2, 0, 1, '', '', 1782610203758, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (29, 'menu.i18n-lang', 'i18n-lang', '/i18n-lang', 1, 'DEFAULT_LAYOUT', 1, 'icon-language', 0, 1, 8, 1, '', '', 1782616287984, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (31, 'menu.i18n-lang.lang-config', 'lang-config', '/lang-config', 0, 'i18n-lang/lang-config/index', 1, '', 29, 2, 0, 1, '', '', 1782616400628, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (32, 'menu.content-setting', 'content-setting', '/content-setting', 1, 'DEFAULT_LAYOUT', 1, 'icon-book', 0, 1, 9, 1, '', '', 1782616837943, 1782616906899);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (33, 'menu.sys-setting.sys-param', 'sys-param', '/sys-param', 0, 'sys-setting/sys-param/index', 1, '', 11, 2, 0, 1, '', '', 1782617966303, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (34, 'menu.content-setting.company-profile', 'company-profile', '/company-profile', 0, 'content-setting/company-profile/index', 1, '', 32, 2, 0, 1, '', '', 1782618303615, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (35, 'menu.content-setting.platform-profile', 'platform-profile', '/platform-profile', 0, 'content-setting/platform-profile/index', 1, '', 32, 2, 1, 1, '', '', 1782618364724, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (36, 'menu.content-setting.regulator', 'regulator', '/regulator', 0, 'content-setting/regulator/index', 1, '', 32, 2, 2, 1, '', '', 1782618446844, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (37, 'menu.content-setting.notices', 'notices', '/notices', 0, 'content-setting/notices/index', 1, '', 32, 2, 3, 1, '', '', 1782618491213, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (38, 'menu.content-setting.user-agreement', 'user-agreement', '/user-agreement', 0, 'content-setting/user-agreement/index', 1, '', 32, 2, 4, 1, '', '', 1782618537789, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (39, 'menu.content-setting.user-privacy', 'user-privacy', '/user-privacy', 0, 'content-setting/user-privacy/index', 1, '', 32, 2, 5, 1, '', '', 1782618585987, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (40, 'menu.sys-log', 'sys-log', '/sys-log', 1, 'DEFAULT_LAYOUT', 1, 'icon-file', 0, 1, 10, 1, '', '', 1782618932767, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (41, 'menu.sys-log.operation', 'operation-log', '/operation-log', 0, 'sys-log/operation/index', 1, '', 40, 2, 0, 1, '', '', 1782619341316, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (42, 'menu.user-member.vip-config', 'vip-config', '/vip-config', 0, 'user-member/vip-config/index', 1, '', 6, 2, 10, 1, '', '', 1782880000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (43, 'menu.user-member.invite-commission', 'invite-commission', '/invite-commission', 0, 'user-member/invite-commission/index', 1, '', 6, 2, 11, 1, '', '', 1782897000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (44, 'menu.user-member.member-groups', 'member-groups', '/member-groups', 0, 'user-member/member-feature/index', 1, '', 6, 2, 1, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (45, 'menu.user-member.member-log', 'member-log', '/member-log', 0, 'user-member/member-feature/index', 1, '', 6, 2, 2, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (46, 'menu.user-member.member-flow', 'member-flow', '/member-flow', 0, 'user-member/member-feature/index', 1, '', 6, 2, 3, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (47, 'menu.user-member.site-message', 'site-message', '/site-message', 0, 'user-member/member-feature/index', 1, '', 6, 2, 4, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (48, 'menu.user-member.telegram-info', 'telegram-info', '/telegram-info', 0, 'user-member/member-feature/index', 1, '', 6, 2, 5, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (53, 'menu.user-member.bot-config', 'bot-config', '/bot-config', 0, 'user-member/bot-config/index', 1, '', 6, 2, 6, 1, '', '', 1783046500000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (49, 'menu.user-member.balance-record', 'balance-record', '/balance-record', 0, 'user-member/member-feature/index', 1, '', 6, 2, 7, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (50, 'menu.user-member.vip-upgrade-record', 'vip-upgrade-record', '/vip-upgrade-record', 0, 'user-member/member-feature/index', 1, '', 6, 2, 8, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (51, 'menu.user-member.share-audit', 'share-audit', '/share-audit', 0, 'user-member/member-feature/index', 1, '', 6, 2, 9, 1, '', '', 1783046000000, NULL);
INSERT INTO `manage_menu_info`(`id`, `menu_key`, `name`, `path`, `type`, `component`, `hide_in_menu`, `icon`, `pno`, `menu_level`, `order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (52, 'menu.user-member.test-account', 'test-account', '/test-account', 0, 'user-member/member-feature/index', 1, '', 6, 2, 10, 1, '', '', 1783046000000, NULL);

INSERT INTO `admin_system_param`(`id`, `param_key`, `param_value`, `description`, `sort_order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (1, 'i18n.default', 'zh-CN', '后台默认语言编码', 0, 1, '', '', 1782903000000, NULL);
INSERT INTO `admin_system_param`(`id`, `param_key`, `param_value`, `description`, `sort_order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (2, 'i18n.lang.zh-CN', '简体中文', '后台可选语言', 10, 1, '', '', 1782903000000, NULL);
INSERT INTO `admin_system_param`(`id`, `param_key`, `param_value`, `description`, `sort_order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (3, 'i18n.lang.en-US', 'English', '后台可选语言', 20, 1, '', '', 1782903000000, NULL);

INSERT INTO `admin_bot_config`(`id`, `bot_name`, `bot_token`, `webhook_url`, `description`, `sort_order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (1, 'Demo Telegram Bot', '123456789:demo_token_for_local_seed_only', '', '本地演示机器人配置，不调用 Telegram API', 0, 1, '', '', 1783046500000, NULL);
INSERT INTO `admin_bot_auto_reply`(`id`, `bot_id`, `keyword`, `reply_content`, `match_type`, `sort_order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (1, 1, '/start', '欢迎使用任务平台，请在前台页面查看任务和钱包。', 2, 0, 1, '', '', 1783046500000, NULL);
INSERT INTO `admin_bot_auto_reply`(`id`, `bot_id`, `keyword`, `reply_content`, `match_type`, `sort_order`, `status`, `creator`, `updater`, `create_time`, `update_time`) VALUES (2, 1, '客服', '如需帮助，请联系在线客服。', 1, 10, 1, '', '', 1783046500000, NULL);

